//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public System.Guid Id { get; set; }
        public string Manufacturer { get; set; }
    }
}
